// src/data/chefs.js
const Chefs = [
  {
    id: 1,
    name: "Mr. Shiv Poojan",
    rating: 4.7,
    ratingsCount: 797,
    image: "https://storage.googleapis.com/chefkartimages/cook-profile/9039-ppoja.png",
    address: "Emerald Hills(Coral), Sector 65, Gurgaon",
    locations: 16,
    phone: "+91-62XXXXXXX",
    experience: "15 Years of exp" ,
    city: "gurgaon",
    area: "sector 65",
    locality: "emerald hills",
    verified: true,
  },
  {
    id: 2,
    name: "Mr. Prakash Baitha",
    rating: 4.7,
    ratingsCount: 556,
    image: "https://storage.googleapis.com/chefkartimages/cook-profile/38340-fd.png",
    address: "Galaxy Apartment, Sector 43, Gurgaon",
    locations: 7,
    phone: "+91-86XXXXXXX",
    experience: "9 Years of exp",
    city: "gurgaon",
    area: "sector 43",
    locality: "galaxy apartment",
    verified: true,
  },
  {
    id: 3,
    name: "Mr. Shatrughan",
    rating: 4.7,
    ratingsCount: 556,
    image: "https://storage.googleapis.com/chefkartimages/cook-profile/40143-shatrugan.png",
    address: "M3M Golfestate Fairway East,  Sector 65, Gurgaon, 8+ locations",
    locations: 7,
    phone: "+91-98XXXXXXX",
    experience: "8 Years of exp",
    city: "gurgaon",
    area: "sector 43",
    locality: "galaxy apartment",
    verified: true,
  },
 
  {
    id: 4,
    name: "Mr. Ashish Kumar  Gupta",
    rating: 4.7,
    ratingsCount: 556,
    image: "https://storage.googleapis.com/chefkartimages/cook-profile/8800-WhatsApp_Image_2024-11-01_at_1.02.28_PM-removebg-preview.png",
    address: "M2K symphony floors,  Sector 51, Gurgaon, 5+ locations",
    locations: 7,
    phone: "+91-98XXXXXXX",
    experience: "9 Years of exp",
    city: "gurgaon",
    area: "sector 43",
    locality: "galaxy apartment",
    verified: true,
  },
  {
    id: 5,
    name: "Mr. Pramod Ravidas",
    rating: 4.7,
    ratingsCount: 556,
    image: "https://storage.googleapis.com/chefkartimages/cook-profile/56095-WhatsApp_Image_2025-04-23_at_3.56.35_PM-removebg-preview.png",
    address: "Emerald Hills(Coral),  Sector 65, Gurgaon, 7+ locations",
    locations: 7,
    phone: "+91-94XXXXXXX",
    experience: "10 Years of exp",
    city: "gurgaon",
    area: "sector 43",
    locality: "galaxy apartment",
    verified: true,
  },
 
];

export default Chefs;
